import { createHash, randomUUID } from 'node:crypto'
import { constants as fsConstants, existsSync } from 'node:fs'
import { copyFile, lstat, mkdir, open, readFile, readdir, realpath, rename, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { spawn } from 'node:child_process'
import net from 'node:net'
import type { ManagedRuntimeCommandResult, ManagedRuntimeCommandRunner } from './managedRuntime'
import {
  MANAGED_RUNTIME_OVERLAY_FILE,
  buildManagedRuntimeGuestOverlay,
  type ManagedRuntimeGuestOverlay
} from './managedRuntimeGuestOverlay'

export interface ManagedHyperVRuntimeOptions {
  userData: string
  installId: string
  runtimeId: string
  runtimeVersion: string
  runner?: ManagedRuntimeCommandRunner
  guest?: ManagedHyperVGuestTransport
  now?: () => Date
}

export interface ManagedHyperVReleaseImage {
  file: string
  sha256: string
  sizeBytes: number
}

export interface ManagedHyperVGuestStatus {
  owner: 'devhotel'
  installId: string
  runtimeId: string
  runtimeVersion: string
  daemonVersion: string
  state: 'ready'
}

/**
 * Where the guest serves the Room command channel, and the secret that opens it.
 *
 * Both are per-boot facts, which is why they are asked for rather than stored:
 * the address comes from DHCP on the runtime's private NIC and the token is
 * regenerated by the guest, so a value cached from a previous boot would point
 * the Host at nothing — or, worse, at whatever now holds that address.
 */
export interface ManagedHyperVGuestChannel {
  owner: 'devhotel'
  state: 'ready'
  address: string
  port: number
  token: string
}

export interface ManagedHyperVGuestTransport {
  health(pipePath: string): Promise<ManagedHyperVGuestStatus>
  /**
   * Resolves once the guest has both an address and a token. Optional so a
   * health-only transport — the one #106 shipped, and every test double built
   * against it — stays valid.
   */
  channel?(pipePath: string): Promise<ManagedHyperVGuestChannel>
}

export interface ManagedHyperVRuntimeMarker {
  schemaVersion: 2
  owner: 'devhotel'
  backend: 'hyper-v'
  installId: string
  runtimeId: string
  runtimeVersion: string
  vmName: string
  vmId: string | null
  vmPath: string
  /** Owned, immutable copy of the pinned Alpine boot ISO. */
  isoPath: string
  /** Disposable FAT disk carrying the DevHotel apkovl overlay. */
  seedPath: string
  /** Persistent Room and runtime state; never rebuilt by a repair. */
  statePath: string
  pipePath: string
  /** SHA-256 of the pinned boot ISO. */
  baseImageDigest: string
  /** SHA-256 of the generated overlay, binding the guest identity payload. */
  overlayDigest: string
  /**
   * Whether this Host actually granted nested virtualization to the VM.
   *
   * Hyper-V refuses it on hosts that cannot nest, and the refusal is
   * survivable -- the runtime boots and serves Web Rooms without it. What is
   * not survivable is losing the answer: only a guest that was granted it can
   * run KVM-backed Android emulators, so a later feature has to read what this
   * Host decided rather than re-derive it. `null` is a marker written before
   * this was recorded, and means unknown rather than refused.
   */
  nestedVirtualization?: boolean | null
  status: 'provisioning' | 'stopped' | 'starting' | 'ready' | 'broken'
  createdAt: string
  updatedAt: string
  failure?: string
}

export interface ManagedHyperVRuntimeObservation {
  state: 'not-installed' | 'preparing' | 'stopped' | 'ready' | 'broken'
  runtimeId: string | null
  runtimeVersion: string | null
  daemonVersion: string | null
  baseImageDigest: string | null
  /** What this Host granted at creation. `null` means unrecorded, not refused. */
  nestedVirtualization: boolean | null
  detail: string
}

/**
 * What a removal request actually did. Uninstall has to tell "there was
 * nothing of ours here" apart from "something is here that DevHotel cannot
 * prove it owns", because only the second leaves a Hyper-V object behind.
 */
export type ManagedHyperVRemovalOutcome = 'nothing-owned' | 'removed' | 'refused'

interface HyperVInspection {
  exists: boolean
  id: string | null
  state: string | null
  notes: string | null
}

const MARKER_FILE = 'provider.json'
const POWERSHELL_ARGS = ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-EncodedCommand'] as const

function isDigest(value: string): boolean {
  return /^[a-f0-9]{64}$/.test(value)
}

function isOpaqueId(value: string): boolean {
  return /^[0-9A-Za-z._-]{8,128}$/.test(value)
}

function psLiteral(value: string): string {
  return `'${value.replaceAll("'", "''")}'`
}

function encodedPowerShell(script: string): string[] {
  return [...POWERSHELL_ARGS, Buffer.from(script, 'utf16le').toString('base64')]
}

/** `NT VIRTUAL MACHINE\Virtual Machines`, the group every VM worker account joins. */
const HYPERV_VM_GROUP_SID = 'S-1-5-83-0'

/**
 * Every directory from the volume root down to `leaf`, outermost first.
 *
 * A Hyper-V VM worker process runs as a per-VM virtual account that belongs to
 * no ordinary group, so it cannot traverse a user profile path such as
 * `%APPDATA%\devhotel\runtime\managed-linux`. Hyper-V grants the VM access to
 * the attachment *files* when they are added, but a file it cannot reach still
 * fails the VM start with "failed to open attachment … Access is denied", so
 * the ancestors have to be walked and granted explicitly.
 */
function ancestorChain(leaf: string): string[] {
  const chain: string[] = []
  let current = path.resolve(leaf)
  for (;;) {
    chain.push(current)
    const parent = path.dirname(current)
    if (parent === current) break
    current = parent
  }
  return chain.reverse()
}

function defaultRunner(executable: string, args: readonly string[]): Promise<ManagedRuntimeCommandResult> {
  return new Promise((resolve) => {
    const child = spawn(executable, [...args], { windowsHide: true })
    let stdout = ''
    let stderr = ''
    let settled = false
    const finish = (result: ManagedRuntimeCommandResult): void => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      resolve(result)
    }
    const timer = setTimeout(() => {
      child.kill()
      finish({ code: -1, stdout, stderr: `${stderr}Managed Hyper-V command timed out.` })
    }, 120_000)
    child.stdout.setEncoding('utf8')
    child.stderr.setEncoding('utf8')
    child.stdout.on('data', (chunk) => (stdout += chunk))
    child.stderr.on('data', (chunk) => (stderr += chunk))
    child.on('error', (error) => finish({ code: -1, stdout, stderr: `${stderr}${error.message}` }))
    child.on('close', (code) => finish({ code: code ?? -1, stdout, stderr }))
  })
}

function parseJsonRecord(stdout: string, message: string): Record<string, unknown> {
  try {
    const value: unknown = JSON.parse(stdout.trim())
    if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(message)
    return value as Record<string, unknown>
  } catch {
    throw new Error(message)
  }
}

async function sha256File(file: string): Promise<{ digest: string; sizeBytes: number }> {
  const handle = await open(file, 'r')
  try {
    const before = await handle.stat()
    if (!before.isFile()) throw new Error('Managed runtime image is not a regular file')
    const hash = createHash('sha256')
    for await (const chunk of handle.createReadStream({ autoClose: false })) hash.update(chunk)
    const after = await handle.stat()
    if (after.size !== before.size || after.mtimeMs !== before.mtimeMs) {
      throw new Error('Managed runtime image changed during verification')
    }
    return { digest: hash.digest('hex'), sizeBytes: after.size }
  } finally {
    await handle.close()
  }
}

function markerNotes(marker: ManagedHyperVRuntimeMarker): string {
  return JSON.stringify({
    schemaVersion: 2,
    owner: marker.owner,
    backend: marker.backend,
    installId: marker.installId,
    runtimeId: marker.runtimeId,
    runtimeVersion: marker.runtimeVersion,
    vmPath: marker.vmPath,
    isoPath: marker.isoPath,
    seedPath: marker.seedPath,
    statePath: marker.statePath,
    pipePath: marker.pipePath,
    baseImageDigest: marker.baseImageDigest,
    overlayDigest: marker.overlayDigest
  })
}

function assertExactPath(actual: unknown, expected: string): boolean {
  return typeof actual === 'string' && path.resolve(actual).toLocaleLowerCase('en-US') === path.resolve(expected).toLocaleLowerCase('en-US')
}

function validateNotes(raw: string | null, marker: ManagedHyperVRuntimeMarker): boolean {
  if (!raw) return false
  try {
    const value = JSON.parse(raw) as Record<string, unknown>
    return (
      value['schemaVersion'] === 2 &&
      value['owner'] === 'devhotel' &&
      value['backend'] === 'hyper-v' &&
      value['installId'] === marker.installId &&
      value['runtimeId'] === marker.runtimeId &&
      value['runtimeVersion'] === marker.runtimeVersion &&
      value['baseImageDigest'] === marker.baseImageDigest &&
      value['overlayDigest'] === marker.overlayDigest &&
      value['pipePath'] === marker.pipePath &&
      assertExactPath(value['vmPath'], marker.vmPath) &&
      assertExactPath(value['isoPath'], marker.isoPath) &&
      assertExactPath(value['seedPath'], marker.seedPath) &&
      assertExactPath(value['statePath'], marker.statePath)
    )
  } catch {
    return false
  }
}

function validateMarker(value: unknown, expected: Omit<ManagedHyperVRuntimeOptions, 'runner' | 'guest' | 'now'>): ManagedHyperVRuntimeMarker {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('Managed Hyper-V ownership marker is invalid')
  const marker = value as Partial<ManagedHyperVRuntimeMarker>
  if (
    marker.schemaVersion !== 2 ||
    marker.owner !== 'devhotel' ||
    marker.backend !== 'hyper-v' ||
    marker.installId !== expected.installId ||
    marker.runtimeId !== expected.runtimeId ||
    marker.runtimeVersion !== expected.runtimeVersion ||
    typeof marker.vmName !== 'string' ||
    !/^DevHotel-[a-f0-9]{16}$/.test(marker.vmName) ||
    (marker.vmId !== null && (typeof marker.vmId !== 'string' || !/^[a-f0-9-]{36}$/i.test(marker.vmId))) ||
    typeof marker.vmPath !== 'string' ||
    typeof marker.isoPath !== 'string' ||
    typeof marker.seedPath !== 'string' ||
    typeof marker.statePath !== 'string' ||
    typeof marker.pipePath !== 'string' ||
    !/^\\\\\.\\pipe\\devhotel-runtime-[a-f0-9]{16}$/.test(marker.pipePath) ||
    typeof marker.baseImageDigest !== 'string' ||
    !isDigest(marker.baseImageDigest) ||
    typeof marker.overlayDigest !== 'string' ||
    !isDigest(marker.overlayDigest) ||
    (marker.nestedVirtualization !== undefined &&
      marker.nestedVirtualization !== null &&
      typeof marker.nestedVirtualization !== 'boolean') ||
    !['provisioning', 'stopped', 'starting', 'ready', 'broken'].includes(marker.status ?? '') ||
    typeof marker.createdAt !== 'string' ||
    typeof marker.updatedAt !== 'string'
  ) {
    throw new Error('Managed Hyper-V ownership marker is invalid')
  }
  return marker as ManagedHyperVRuntimeMarker
}

/**
 * Owns the first separate-kernel Windows substrate. Hyper-V object names and
 * paths remain backend-private; callers observe only the product runtime
 * identity, version, digest, health and recovery state.
 */
export class ManagedHyperVRuntime {
  private readonly root: string
  private readonly markerPath: string
  private readonly installId: string
  private readonly runtimeId: string
  private readonly runtimeVersion: string
  private readonly runner: ManagedRuntimeCommandRunner
  private readonly guest?: ManagedHyperVGuestTransport
  private readonly now: () => Date
  private readonly vmName: string
  private readonly vmPath: string
  private readonly seedPath: string
  private readonly statePath: string
  private readonly pipePath: string
  private readonly overlay: ManagedRuntimeGuestOverlay

  constructor(opts: ManagedHyperVRuntimeOptions) {
    if (!isOpaqueId(opts.installId) || !isOpaqueId(opts.runtimeId) || !/^[0-9A-Za-z._-]{1,64}$/.test(opts.runtimeVersion)) {
      throw new Error('Managed Hyper-V identity is invalid')
    }
    this.root = path.resolve(opts.userData, 'runtime', 'managed-linux', 'hyperv')
    this.markerPath = path.join(this.root, MARKER_FILE)
    this.installId = opts.installId
    this.runtimeId = opts.runtimeId
    this.runtimeVersion = opts.runtimeVersion
    this.runner = opts.runner ?? defaultRunner
    this.guest = opts.guest
    this.now = opts.now ?? (() => new Date())
    const suffix = createHash('sha256').update(`${opts.installId}\0${opts.runtimeId}`).digest('hex').slice(0, 16)
    this.vmName = `DevHotel-${suffix}`
    this.vmPath = path.join(this.root, 'machine')
    this.statePath = path.join(this.vmPath, 'state.vhdx')
    this.seedPath = path.join(this.vmPath, 'seed.vhdx')
    this.pipePath = `\\\\.\\pipe\\devhotel-runtime-${suffix}`
    this.overlay = buildManagedRuntimeGuestOverlay({
      installId: this.installId,
      runtimeId: this.runtimeId,
      runtimeVersion: this.runtimeVersion,
      daemonVersion: this.runtimeVersion
    })
  }

  async readMarker(): Promise<ManagedHyperVRuntimeMarker | null> {
    return await this.readMarkerAs(this.runtimeVersion)
  }

  /**
   * The marker, read as if this install were at `runtimeVersion`.
   *
   * Only a migration has any business asking: every other caller wants the
   * marker to match the version it was constructed for, and a mismatch there
   * is exactly the "a build silently re-stamped a live runtime" case the
   * validation exists to catch.
   */
  private async readMarkerAs(runtimeVersion: string): Promise<ManagedHyperVRuntimeMarker | null> {
    if (!existsSync(this.markerPath)) return null
    const root = await realpath(this.root)
    const info = await lstat(this.markerPath)
    if (!info.isFile() || info.isSymbolicLink()) throw new Error('Managed Hyper-V ownership marker is not a regular file')
    const canonicalMarker = await realpath(this.markerPath)
    if (path.dirname(canonicalMarker).toLocaleLowerCase('en-US') !== root.toLocaleLowerCase('en-US')) {
      throw new Error('Managed Hyper-V ownership marker escaped its runtime root')
    }
    const marker = validateMarker(JSON.parse(await readFile(canonicalMarker, 'utf8')), {
      userData: path.dirname(path.dirname(path.dirname(this.root))),
      installId: this.installId,
      runtimeId: this.runtimeId,
      runtimeVersion
    })
    if (
      !assertExactPath(marker.vmPath, this.vmPath) ||
      !assertExactPath(marker.seedPath, this.seedPath) ||
      !assertExactPath(marker.statePath, this.statePath) ||
      marker.pipePath !== this.pipePath
    ) {
      throw new Error('Managed Hyper-V ownership marker paths are invalid')
    }
    return marker
  }

  async provision(image: ManagedHyperVReleaseImage): Promise<ManagedHyperVRuntimeMarker> {
    if (!isDigest(image.sha256) || !Number.isSafeInteger(image.sizeBytes) || image.sizeBytes < 1) {
      throw new Error('Managed Hyper-V release image metadata is invalid')
    }
    const sourceInfo = await lstat(image.file)
    if (!sourceInfo.isFile() || sourceInfo.isSymbolicLink()) throw new Error('Managed Hyper-V release image is not a regular file')
    const source = await realpath(image.file)
    const measured = await sha256File(source)
    if (measured.digest !== image.sha256 || measured.sizeBytes !== image.sizeBytes) {
      throw new Error('Managed Hyper-V release image verification failed')
    }

    await this.ensureRoot()
    const ownedImage = await this.installImage(source, image)
    let marker = await this.readMarker()
    const inspection = await this.inspectVm()
    if (!marker && inspection.exists) throw new Error('Managed Hyper-V VM name collides with an unowned VM')

    if (!marker) {
      const now = this.now().toISOString()
      marker = await this.writeMarker({
        schemaVersion: 2,
        owner: 'devhotel',
        backend: 'hyper-v',
        installId: this.installId,
        runtimeId: this.runtimeId,
        runtimeVersion: this.runtimeVersion,
        vmName: this.vmName,
        vmId: null,
        vmPath: this.vmPath,
        isoPath: ownedImage,
        seedPath: this.seedPath,
        statePath: this.statePath,
        pipePath: this.pipePath,
        baseImageDigest: image.sha256,
        overlayDigest: this.overlay.sha256,
        status: 'provisioning',
        createdAt: now,
        updatedAt: now
      })
    } else if (marker.baseImageDigest !== image.sha256) {
      throw new Error('Managed Hyper-V runtime update requires an explicit migration')
    } else if (marker.overlayDigest !== this.overlay.sha256) {
      // The overlay is derived from the fenced identity, so a digest change can
      // only mean this build generates a different guest bootstrap. That is a
      // runtime change, and it has to be migrated deliberately rather than
      // silently re-seeded underneath a running install.
      throw new Error('Managed Hyper-V guest overlay changed; a runtime version bump is required')
    }

    if (inspection.exists) {
      this.assertOwnedVm(inspection, marker)
      if (!marker.vmId) marker = await this.writeMarker({ ...marker, vmId: inspection.id, status: 'stopped', failure: undefined })
      return marker
    }

    const create = await this.runPowerShell(
      [
        `$vmName=${psLiteral(marker.vmName)}`,
        `$vmPath=${psLiteral(marker.vmPath)}`,
        `$isoPath=${psLiteral(marker.isoPath)}`,
        `$seedPath=${psLiteral(marker.seedPath)}`,
        `$statePath=${psLiteral(marker.statePath)}`,
        `$pipePath=${psLiteral(marker.pipePath)}`,
        `$notes=${psLiteral(markerNotes(marker))}`,
        `$overlayName=${psLiteral(MANAGED_RUNTIME_OVERLAY_FILE)}`,
        `$overlayB64=${psLiteral(this.overlay.bytes.toString('base64'))}`,
        `$traverse=@(${ancestorChain(this.vmPath).map(psLiteral).join(',')})`,
        "if (Get-VM -Name $vmName -ErrorAction SilentlyContinue) { throw 'Managed runtime VM collision' }",
        'New-Item -ItemType Directory -Force -Path $vmPath | Out-Null',
        // Traverse only, and never inherited: this lets a VM worker account
        // resolve a path down to its own attachments without being able to
        // list these directories or read anything else inside them.
        `foreach ($dir in $traverse) { & icacls $dir /grant ${psLiteral(`*${HYPERV_VM_GROUP_SID}:(X)`)} | Out-Null }`,
        // With no VM object, exact retained ownership authorizes rebuilding the
        // seed, which is disposable and regenerated from the marker identity.
        // The state disk is never destroyed here: it holds Room data, and a
        // power loss during first provision must not cost the user that.
        'if (Test-Path -LiteralPath $seedPath) { Dismount-VHD -Path $seedPath -ErrorAction SilentlyContinue; Remove-Item -LiteralPath $seedPath -Force -ErrorAction Stop }',
        'if (-not (Test-Path -LiteralPath $statePath)) { New-VHD -Path $statePath -Dynamic -SizeBytes 64GB | Out-Null }',
        'New-VHD -Path $seedPath -Dynamic -SizeBytes 64MB | Out-Null',
        '$seedDisk=Mount-VHD -Path $seedPath -Passthru',
        'try {',
        '  $seedDisk | Initialize-Disk -PartitionStyle MBR -PassThru | Out-Null',
        '  $partition=$seedDisk | New-Partition -UseMaximumSize -AssignDriveLetter',
        "  $volume=$partition | Format-Volume -FileSystem FAT -NewFileSystemLabel 'DEVHOTEL' -Confirm:$false",
        '  $drive=($volume.DriveLetter + ":\\")',
        '  [IO.File]::WriteAllBytes((Join-Path $drive $overlayName),[Convert]::FromBase64String($overlayB64))',
        '} finally { Dismount-VHD -Path $seedPath -ErrorAction SilentlyContinue }',
        // The guest runs from the pinned read-only ISO, so the boot media can
        // never drift from its verified digest.
        '$vm=New-VM -Name $vmName -Generation 2 -MemoryStartupBytes 4GB -Path $vmPath -NoVHD',
        '$dvd=Add-VMDvdDrive -VM $vm -Path $isoPath -Passthru',
        'Add-VMHardDiskDrive -VM $vm -ControllerType SCSI -Path $statePath',
        'Add-VMHardDiskDrive -VM $vm -ControllerType SCSI -Path $seedPath',
        // Nested virtualization is what would later let the guest run KVM for
        // Android emulators. It is not needed to boot the runtime or to serve
        // Web Rooms, and Hyper-V refuses it on hosts that cannot nest -- which
        // includes running inside a VM at all, since it does not stack three
        // levels deep. Left bare, the refusal is a non-terminating error this
        // provider neither sees nor acts on, so the VM quietly loses a
        // capability nobody recorded. Asking for it explicitly, and falling
        // back, makes both outcomes deliberate and observable.
        '$nested=$false',
        'try { Set-VMProcessor -VM $vm -Count 4 -ExposeVirtualizationExtensions $true -ErrorAction Stop; $nested=$true }',
        'catch { Set-VMProcessor -VM $vm -Count 4 -ErrorAction Stop }',
        'Set-VMFirmware -VM $vm -EnableSecureBoot Off -FirstBootDevice $dvd',
        'Set-VMComPort -VM $vm -Number 2 -Path $pipePath',
        // The runtime needs one network path, for two things it cannot do
        // without: reach the Host so Rooms can be driven at all, and resolve
        // the pinned guest packages and Room base images on first provision.
        //
        // The Default Switch is what makes that a NAT'd private network rather
        // than a bridge onto the user's LAN, and it is the only switch Hyper-V
        // creates and maintains itself — creating one would mean DevHotel owning
        // a Host network object, with its own uninstall and collision problems.
        // A Host without it is reported rather than worked around, because the
        // alternative is a runtime that boots and can never serve a Room.
        "$switch=Get-VMSwitch -Name 'Default Switch' -ErrorAction SilentlyContinue",
        "if (-not $switch) { throw 'Managed runtime requires the Hyper-V Default Switch' }",
        "Get-VMNetworkAdapter -VM $vm | Connect-VMNetworkAdapter -SwitchName 'Default Switch'",
        'Set-VM -VM $vm -Notes $notes -AutomaticStartAction StartIfRunning -AutomaticStopAction Save',
        '[pscustomobject]@{Id=$vm.Id.Guid;State=[string]$vm.State;Nested=$nested}|ConvertTo-Json -Compress'
      ].join(';')
    )
    const created = parseJsonRecord(create, 'Managed Hyper-V provider returned invalid creation evidence')
    if (typeof created['Id'] !== 'string') throw new Error('Managed Hyper-V provider did not return a VM identity')
    const after = await this.inspectVm()
    this.assertOwnedVm(after, marker)
    return await this.writeMarker({
      ...marker,
      vmId: after.id,
      // Recorded, not asserted. A Host that refused is still a valid runtime;
      // what would be wrong is finishing provisioning with no record of which
      // of the two happened.
      nestedVirtualization: typeof created['Nested'] === 'boolean' ? created['Nested'] : null,
      status: 'stopped',
      failure: undefined
    })
  }

  /**
   * Moves an owned runtime from `fromVersion` onto this provider's version,
   * keeping the disk the Room data is on.
   *
   * The VM object cannot be edited into the new version: its boot media, its
   * seeded guest identity and its ownership Notes all change together, and a
   * saved state taken against the old guest cannot be resumed against the new
   * one. So the object is proved owned at the old version, destroyed, and
   * rebuilt at the new one — while `state.vhdx`, which is where Rooms actually
   * live, is neither detached nor recreated. The rebuild path is the ordinary
   * provisioning path, which already reuses an existing state disk and treats
   * the seed as disposable; that reuse is the guarantee, not a coincidence.
   *
   * Every step is idempotent, because the interesting failures are the ones
   * that happen between steps. A crash after the VM is gone but before the new
   * marker lands re-runs from the old marker; a crash after the marker lands
   * re-runs from the new one. Both converge on the same runtime.
   *
   * The same call runs a rollback: a rollback is a migration whose target is
   * the version the install came from.
   */
  async migrateFrom(fromVersion: string, image: ManagedHyperVReleaseImage): Promise<ManagedHyperVRuntimeMarker> {
    if (!/^[0-9A-Za-z._-]{1,64}$/.test(fromVersion)) throw new Error('Managed Hyper-V migration source version is invalid')
    if (fromVersion === this.runtimeVersion) throw new Error('Managed Hyper-V migration has nothing to change')

    // Already carrying this provider's version: a previous attempt got past the
    // marker swap, so finishing is the recovery.
    if (await this.readMarkerAs(this.runtimeVersion).catch(() => null)) return await this.provision(image)

    const previous = await this.readMarkerAs(fromVersion).catch(() => null)
    // Nothing owned at either version is not a migration failure — there is no
    // runtime to move — so it provisions the target version outright.
    if (!previous) return await this.provision(image)

    // Both versions derive these from the same fenced identity, so a mismatch
    // means the marker is not describing this install's runtime, and a
    // migration that "preserves" the wrong disk preserves nothing.
    if (!assertExactPath(previous.statePath, this.statePath) || !assertExactPath(previous.vmPath, this.vmPath)) {
      throw new Error('Managed Hyper-V migration would not preserve the Room state disk')
    }

    const sourceInfo = await lstat(image.file)
    if (!sourceInfo.isFile() || sourceInfo.isSymbolicLink()) throw new Error('Managed Hyper-V release image is not a regular file')
    await this.ensureRoot()
    const ownedImage = await this.installImage(await realpath(image.file), image)

    const inspection = await this.inspectVm()
    if (inspection.exists) {
      this.assertOwnedVm(inspection, previous)
      await this.runPowerShell(
        [
          `$vmName=${psLiteral(previous.vmName)}`,
          `$vmId=${psLiteral(previous.vmId ?? '')}`,
          `$notes=${psLiteral(markerNotes(previous))}`,
          `$seedPath=${psLiteral(previous.seedPath)}`,
          '$vm=Get-VM -Name $vmName -ErrorAction SilentlyContinue',
          'if ($null -ne $vm) {',
          // Re-proved inside the pass that destroys it, exactly as removal
          // does: between the inspection above and this command the object
          // could have been renamed onto or away from this name.
          "  if ($vm.Notes -ne $notes) { throw 'Managed Hyper-V VM ownership proof is invalid' }",
          "  if ($vmId -ne '' -and $vm.Id.Guid -ne $vmId) { throw 'Managed Hyper-V VM identity changed' }",
          // Turned off rather than saved: a saved state belongs to the guest
          // that is being replaced, and resuming it against new boot media is
          // what would actually corrupt the state disk.
          "  if ([string]$vm.State -ne 'Off') { Stop-VM -VM $vm -TurnOff -Force -ErrorAction Stop }",
          // -Force only removes the registration. The VHDX files stay, which is
          // the point: state.vhdx is never named here at all.
          '  Remove-VM -VM $vm -Force -ErrorAction Stop',
          '}',
          // The seed is regenerated from the new identity, so the old one is
          // removed with the VM that held it open. It carries no Room data.
          'if (Test-Path -LiteralPath $seedPath) { Dismount-VHD -Path $seedPath -ErrorAction SilentlyContinue; Remove-Item -LiteralPath $seedPath -Force -ErrorAction Stop }',
          '[pscustomobject]@{Migrated=$true}|ConvertTo-Json -Compress'
        ].join(';')
      )
    }

    await this.writeMarker({
      ...previous,
      runtimeVersion: this.runtimeVersion,
      isoPath: ownedImage,
      baseImageDigest: image.sha256,
      overlayDigest: this.overlay.sha256,
      // The object that carried the old identity is gone; the new one has not
      // been created yet, and claiming its predecessor's ID would defeat the
      // identity check that authorises every later mutation.
      vmId: null,
      status: 'provisioning',
      failure: undefined
    })
    return await this.provision(image)
  }

  /**
   * Deletes owned boot images no marker points at any more.
   *
   * Only files this provider itself wrote: they live in one directory it
   * created, and it names them by the digest it verified, so an entry that is
   * neither the live image nor a `<sha256>.iso` name is left alone rather than
   * guessed about. Called after an update commits, because until then the
   * previous image is what a rollback would need.
   */
  async pruneUnreferencedImages(): Promise<number> {
    const marker = await this.readMarker().catch(() => null)
    if (!marker) return 0
    const imageRoot = path.join(this.root, 'images')
    if (!existsSync(imageRoot)) return 0
    const info = await lstat(imageRoot)
    if (!info.isDirectory() || info.isSymbolicLink()) throw new Error('Managed Hyper-V image root is unsafe')
    const live = path.basename(marker.isoPath).toLocaleLowerCase('en-US')
    let removed = 0
    for (const entry of await readdir(imageRoot)) {
      const name = entry.toLocaleLowerCase('en-US')
      if (name === live || !/^[a-f0-9]{64}\.iso$/.test(name)) continue
      const candidate = path.join(imageRoot, entry)
      const candidateInfo = await lstat(candidate)
      if (!candidateInfo.isFile() || candidateInfo.isSymbolicLink()) continue
      await rm(candidate, { force: true })
      removed += 1
    }
    return removed
  }

  async start(): Promise<ManagedHyperVRuntimeObservation> {
    let marker = await this.requireOwnedVm()
    marker = await this.writeMarker({ ...marker, status: 'starting', failure: undefined })
    try {
      const inspection = await this.inspectVm()
      if (inspection.state?.toLocaleLowerCase('en-US') !== 'running') {
        await this.runPowerShell(`Start-VM -Name ${psLiteral(marker.vmName)} -ErrorAction Stop`)
      }
      const health = await this.requireGuestHealth(marker)
      await this.writeMarker({ ...marker, status: 'ready', failure: undefined })
      return this.readyObservation(marker, health)
    } catch (error) {
      const failure = error instanceof Error ? error.message : String(error)
      await this.writeMarker({ ...marker, status: 'broken', failure })
      throw error
    }
  }

  async repair(image: ManagedHyperVReleaseImage): Promise<ManagedHyperVRuntimeObservation> {
    await this.provision(image)
    return await this.start()
  }

  async stop(): Promise<ManagedHyperVRuntimeObservation> {
    const marker = await this.requireOwnedVm()
    const inspection = await this.inspectVm()
    if (inspection.state?.toLocaleLowerCase('en-US') === 'running') {
      await this.runPowerShell(`Save-VM -Name ${psLiteral(marker.vmName)} -ErrorAction Stop`)
    }
    await this.writeMarker({ ...marker, status: 'stopped', failure: undefined })
    return {
      state: 'stopped',
      runtimeId: marker.runtimeId,
      runtimeVersion: marker.runtimeVersion,
      daemonVersion: null,
      baseImageDigest: marker.baseImageDigest,
      nestedVirtualization: marker.nestedVirtualization ?? null,
      detail: 'The DevHotel-managed runtime is stopped with its state preserved.'
    }
  }

  /**
   * Tears down the runtime this install owns, and refuses to touch anything
   * else.
   *
   * Deleting DevHotel's app data is not enough on Windows: a registered VM
   * keeps its configuration and its VHDX attachments open, so a recursive
   * delete of `%APPDATA%\DevHotel` either fails on the lock or succeeds and
   * leaves Hyper-V holding a VM whose disks no longer exist. The Hyper-V
   * object has to go first, and it can only go if DevHotel can still prove it
   * is the one that made it.
   *
   * Proof is the Host marker plus the exact Notes payload, re-checked inside
   * the same PowerShell pass that removes the VM so nothing can be swapped in
   * between. Without that proof this reports `refused` and removes nothing --
   * an orphan the user can see beats silently deleting a VM that might be
   * theirs.
   */
  async remove(): Promise<ManagedHyperVRemovalOutcome> {
    let marker: ManagedHyperVRuntimeMarker | null
    try {
      marker = await this.readMarker()
    } catch {
      // The marker is the only thing that could authorize removing a VM, so an
      // unreadable one is a refusal rather than a reason to guess.
      return 'refused'
    }
    if (!marker) {
      const inspection = await this.inspectVm().catch(() => null)
      // A VM under DevHotel's derived name with no marker is either a
      // collision or a half-removed install; either way nothing authorizes
      // deleting it.
      return inspection?.exists ? 'refused' : 'nothing-owned'
    }

    const inspection = await this.inspectVm().catch(() => null)
    if (inspection?.exists && !validateNotes(inspection.notes, marker)) return 'refused'
    if (inspection?.exists && inspection.id && marker.vmId && inspection.id.toLocaleLowerCase('en-US') !== marker.vmId.toLocaleLowerCase('en-US')) {
      return 'refused'
    }

    await this.runPowerShell(
      [
        `$vmName=${psLiteral(marker.vmName)}`,
        `$vmId=${psLiteral(marker.vmId ?? '')}`,
        `$notes=${psLiteral(markerNotes(marker))}`,
        `$vmPath=${psLiteral(marker.vmPath)}`,
        '$vm=Get-VM -Name $vmName -ErrorAction SilentlyContinue',
        'if ($null -ne $vm) {',
        // Re-proved here, not just in the caller: between the inspection above
        // and this command the object could have been renamed onto or away
        // from this name.
        "  if ($vm.Notes -ne $notes) { throw 'Managed Hyper-V VM ownership proof is invalid' }",
        "  if ($vmId -ne '' -and $vm.Id.Guid -ne $vmId) { throw 'Managed Hyper-V VM identity changed' }",
        // The user asked to delete everything, so a running guest is turned
        // off rather than saved -- a saved state would only hold the disks
        // open for the removal that follows it.
        "  if ([string]$vm.State -ne 'Off') { Stop-VM -VM $vm -TurnOff -Force -ErrorAction Stop }",
        '  Remove-VM -VM $vm -Force -ErrorAction Stop',
        '}',
        // Only the directory this provider created, and only after the VM that
        // held it open is gone.
        'if (Test-Path -LiteralPath $vmPath) { Remove-Item -LiteralPath $vmPath -Recurse -Force -ErrorAction Stop }',
        '[pscustomobject]@{Removed=$true}|ConvertTo-Json -Compress'
      ].join(';')
    )

    // The owned ISO copy and the marker live under this provider's own root and
    // nowhere else, so removing the root is exactly the owned footprint.
    await rm(this.root, { recursive: true, force: true })
    return 'removed'
  }

  async observe(): Promise<ManagedHyperVRuntimeObservation> {
    try {
      const marker = await this.readMarker()
      if (!marker) {
        return {
          state: 'not-installed',
          runtimeId: null,
          runtimeVersion: null,
          daemonVersion: null,
          baseImageDigest: null,
          nestedVirtualization: null,
          detail: 'The DevHotel-managed Hyper-V runtime is not installed.'
        }
      }
      const inspection = await this.inspectVm()
      this.assertOwnedVm(inspection, marker)
      if (inspection.state?.toLocaleLowerCase('en-US') !== 'running') {
        return {
          state: marker.status === 'broken' ? 'broken' : marker.status === 'provisioning' ? 'preparing' : 'stopped',
          runtimeId: marker.runtimeId,
          runtimeVersion: marker.runtimeVersion,
          daemonVersion: null,
          baseImageDigest: marker.baseImageDigest,
          nestedVirtualization: marker.nestedVirtualization ?? null,
          detail: marker.status === 'broken' ? 'The DevHotel-managed runtime needs repair.' : 'The DevHotel-managed runtime is stopped.'
        }
      }
      const health = await this.requireGuestHealth(marker)
      if (marker.status !== 'ready') await this.writeMarker({ ...marker, status: 'ready', failure: undefined })
      return this.readyObservation(marker, health)
    } catch {
      return {
        state: 'broken',
        runtimeId: null,
        runtimeVersion: null,
        daemonVersion: null,
        baseImageDigest: null,
        nestedVirtualization: null,
        detail: 'The DevHotel-managed runtime ownership or health proof is invalid.'
      }
    }
  }

  private readyObservation(marker: ManagedHyperVRuntimeMarker, health: ManagedHyperVGuestStatus): ManagedHyperVRuntimeObservation {
    return {
      state: 'ready',
      runtimeId: marker.runtimeId,
      runtimeVersion: marker.runtimeVersion,
      daemonVersion: health.daemonVersion,
      baseImageDigest: marker.baseImageDigest,
      nestedVirtualization: marker.nestedVirtualization ?? null,
      detail: 'The DevHotel-managed separate-kernel runtime is ready.'
    }
  }

  private async ensureRoot(): Promise<string> {
    await mkdir(this.root, { recursive: true })
    const info = await lstat(this.root)
    if (!info.isDirectory() || info.isSymbolicLink()) throw new Error('Managed Hyper-V root is not a real directory')
    return await realpath(this.root)
  }

  private async installImage(source: string, image: ManagedHyperVReleaseImage): Promise<string> {
    const imageRoot = path.join(this.root, 'images')
    await mkdir(imageRoot, { recursive: true })
    const imageRootInfo = await lstat(imageRoot)
    if (!imageRootInfo.isDirectory() || imageRootInfo.isSymbolicLink()) throw new Error('Managed Hyper-V image root is unsafe')
    if (path.extname(source).toLocaleLowerCase('en-US') !== '.iso') {
      throw new Error('Managed Hyper-V release image must use the pinned ISO format')
    }
    const target = path.join(imageRoot, `${image.sha256}.iso`)
    if (!existsSync(target)) {
      const temporary = path.join(imageRoot, `.${image.sha256}-${randomUUID()}.tmp`)
      try {
        await copyFile(source, temporary, fsConstants.COPYFILE_EXCL)
        const copied = await sha256File(temporary)
        if (copied.digest !== image.sha256 || copied.sizeBytes !== image.sizeBytes) {
          throw new Error('Managed Hyper-V owned image verification failed')
        }
        await rename(temporary, target)
      } finally {
        await rm(temporary, { force: true })
      }
    }
    const targetInfo = await lstat(target)
    if (!targetInfo.isFile() || targetInfo.isSymbolicLink()) throw new Error('Managed Hyper-V owned image is unsafe')
    const canonical = await realpath(target)
    const measured = await sha256File(canonical)
    if (measured.digest !== image.sha256 || measured.sizeBytes !== image.sizeBytes) {
      throw new Error('Managed Hyper-V owned image no longer matches its release digest')
    }
    return canonical
  }

  private async inspectVm(): Promise<HyperVInspection> {
    const output = await this.runPowerShell(
      [
        `$vm=Get-VM -Name ${psLiteral(this.vmName)} -ErrorAction SilentlyContinue`,
        "if ($null -eq $vm) { [pscustomobject]@{Exists=$false;Id=$null;State=$null;Notes=$null}|ConvertTo-Json -Compress } else { [pscustomobject]@{Exists=$true;Id=$vm.Id.Guid;State=[string]$vm.State;Notes=$vm.Notes}|ConvertTo-Json -Compress }"
      ].join(';')
    )
    const value = parseJsonRecord(output, 'Managed Hyper-V inspection returned invalid evidence')
    return {
      exists: value['Exists'] === true,
      id: typeof value['Id'] === 'string' ? value['Id'] : null,
      state: typeof value['State'] === 'string' ? value['State'] : null,
      notes: typeof value['Notes'] === 'string' ? value['Notes'] : null
    }
  }

  private assertOwnedVm(inspection: HyperVInspection, marker: ManagedHyperVRuntimeMarker): void {
    if (!inspection.exists || !inspection.id || !validateNotes(inspection.notes, marker)) {
      throw new Error('Managed Hyper-V VM ownership proof is invalid')
    }
    if (marker.vmId && inspection.id.toLocaleLowerCase('en-US') !== marker.vmId.toLocaleLowerCase('en-US')) {
      throw new Error('Managed Hyper-V VM identity changed')
    }
  }

  private async requireOwnedVm(): Promise<ManagedHyperVRuntimeMarker> {
    const marker = await this.readMarker()
    if (!marker) throw new Error('Managed Hyper-V ownership marker is missing')
    const inspection = await this.inspectVm()
    this.assertOwnedVm(inspection, marker)
    return marker
  }

  /**
   * Where this install's Rooms are driven, or `null` when the runtime is not
   * usable for Room work yet.
   *
   * Ownership is re-proved before the address is handed out, and it is proved
   * the same three ways every other mutation is: the Host marker, the Hyper-V
   * object's own Notes and ID, and the guest's health identity. Returning a
   * runtime address without that would let a VM that merely answers on the
   * expected pipe receive this install's Room commands.
   */
  async roomChannel(): Promise<ManagedHyperVGuestChannel | null> {
    if (!this.guest?.channel) return null
    const marker = await this.requireOwnedVm()
    const inspection = await this.inspectVm()
    if (inspection.state?.toLocaleLowerCase('en-US') !== 'running') return null
    await this.requireGuestHealth(marker)
    const channel = await this.guest.channel(marker.pipePath)
    if (channel.owner !== 'devhotel' || channel.state !== 'ready') {
      throw new Error('Managed Hyper-V Room command channel proof is invalid')
    }
    return channel
  }

  private async requireGuestHealth(marker: ManagedHyperVRuntimeMarker): Promise<ManagedHyperVGuestStatus> {
    if (!this.guest) throw new Error('Managed Hyper-V private daemon transport is unavailable')
    const health = await this.guest.health(marker.pipePath)
    if (
      health.owner !== 'devhotel' ||
      health.state !== 'ready' ||
      health.installId !== marker.installId ||
      health.runtimeId !== marker.runtimeId ||
      health.runtimeVersion !== marker.runtimeVersion ||
      typeof health.daemonVersion !== 'string' ||
      health.daemonVersion.length === 0
    ) {
      throw new Error('Managed Hyper-V guest identity or health proof is invalid')
    }
    return health
  }

  private async runPowerShell(script: string): Promise<string> {
    const result = await this.runner('powershell.exe', encodedPowerShell(script))
    if (result.code !== 0) {
      throw new Error(result.stderr.trim() || 'Managed Hyper-V provider command failed')
    }
    return result.stdout
  }

  private async writeMarker(marker: ManagedHyperVRuntimeMarker): Promise<ManagedHyperVRuntimeMarker> {
    await this.ensureRoot()
    const next = { ...marker, updatedAt: this.now().toISOString() }
    const temporary = path.join(this.root, `.provider-${randomUUID()}.tmp`)
    try {
      await writeFile(temporary, `${JSON.stringify(next, null, 2)}\n`, { encoding: 'utf8', flag: 'wx' })
      await rename(temporary, this.markerPath)
    } finally {
      await rm(temporary, { force: true })
    }
    return next
  }
}

export class NamedPipeHyperVGuestTransport implements ManagedHyperVGuestTransport {
  constructor(
    private readonly timeoutMs = 120_000,
    private readonly retryMs = 250
  ) {}

  async health(pipePath: string): Promise<ManagedHyperVGuestStatus> {
    return await this.ask<ManagedHyperVGuestStatus>(pipePath, 'health', 'private daemon did not answer', () => true)
  }

  /**
   * Waits for the Room command channel.
   *
   * A guest that has started its agent but not yet finished DHCP, or not yet
   * written this boot's token, answers `preparing`. That is a normal stage of a
   * cold start rather than a failure, so it is retried until the deadline — the
   * same shape the health probe already needs, because that too can be asked
   * before the line exists.
   */
  async channel(pipePath: string): Promise<ManagedHyperVGuestChannel> {
    return await this.ask<ManagedHyperVGuestChannel>(
      pipePath,
      'channel',
      'private daemon has no Room command channel yet',
      (value) =>
        value['state'] === 'ready' &&
        typeof value['address'] === 'string' &&
        /^(?:\d{1,3}\.){3}\d{1,3}$/.test(value['address']) &&
        typeof value['port'] === 'number' &&
        Number.isInteger(value['port']) &&
        value['port'] > 0 &&
        value['port'] < 65_536 &&
        typeof value['token'] === 'string' &&
        /^[a-f0-9]{64}$/.test(value['token'])
    )
  }

  private async ask<T>(
    pipePath: string,
    op: 'health' | 'channel',
    initialError: string,
    accept: (value: Record<string, unknown>) => boolean
  ): Promise<T> {
    if (!/^\\\\\.\\pipe\\devhotel-runtime-[a-f0-9]{16}$/.test(pipePath)) {
      throw new Error('Managed Hyper-V private daemon pipe identity is invalid')
    }
    const deadline = Date.now() + this.timeoutMs
    let lastError = initialError
    while (Date.now() < deadline) {
      try {
        return await this.askOnce<T>(pipePath, op, accept, Math.min(2_000, Math.max(1, deadline - Date.now())))
      } catch (error) {
        lastError = error instanceof Error ? error.message : String(error)
        await new Promise((resolve) => setTimeout(resolve, this.retryMs))
      }
    }
    throw new Error(`Managed Hyper-V ${lastError}`)
  }

  private async askOnce<T>(
    pipePath: string,
    op: 'health' | 'channel',
    accept: (value: Record<string, unknown>) => boolean,
    timeoutMs: number
  ): Promise<T> {
    const requestId = randomUUID().replaceAll('-', '')
    return await new Promise<T>((resolve, reject) => {
      const socket = net.createConnection(pipePath)
      let settled = false
      let buffer = ''
      const finish = (error?: Error, status?: T): void => {
        if (settled) return
        settled = true
        clearTimeout(timer)
        socket.destroy()
        if (error) reject(error)
        else resolve(status!)
      }
      const timer = setTimeout(() => finish(new Error(`private daemon ${op} request timed out`)), timeoutMs)
      socket.setEncoding('utf8')
      socket.on('connect', () => socket.write(`${op}:${requestId}\n`))
      socket.on('data', (chunk) => {
        buffer += chunk
        if (Buffer.byteLength(buffer, 'utf8') > 65_536) {
          finish(new Error('private daemon response exceeded its limit'))
          return
        }
        for (;;) {
          const newline = buffer.indexOf('\n')
          if (newline < 0) return
          const line = buffer.slice(0, newline).trim()
          buffer = buffer.slice(newline + 1)
          if (!line.startsWith('{')) continue
          try {
            const value = parseJsonRecord(line, `private daemon returned invalid ${op} evidence`)
            if (value['requestId'] !== requestId) continue
            if (!accept(value)) {
              finish(new Error(`private daemon is not ready to answer ${op}`))
              return
            }
            finish(undefined, value as unknown as T)
          } catch {
            continue
          }
        }
      })
      socket.on('error', (error) => finish(new Error(`private daemon connection failed: ${error.message}`)))
      socket.on('close', () => finish(new Error(`private daemon closed without ${op} evidence`)))
    })
  }
}
